### ISSUE TITLE
Add Padding in Input Screen

### ISSUE THREAD

**Issue by rhnas110** [sanskarmalkhede/calculator#12]
Hi, Sir @sanskarmalkhede 
Issue Description: 
Currently the values in the inputs are too crowded because they don't have padding, and I plan to tidy up the inputs so they are not too crowded.

Before: 
![image](https://github.com/sanskarmalkhede/calculator/assets/51848196/2a159129-95d7-48e1-bf5d-c9a7d55e87b1)

After: 
![image](https://github.com/sanskarmalkhede/calculator/assets/51848196/032e848b-7bc7-4038-bbea-7ec9e3651b82)

I think it looks better, can you take my advice and assign this task to me? and I'm actually new to open source contributions, I also participated in Hacktoberfest2023.

**Comment by sanskarmalkhede** [comment]
Yeah sure, I will assign you the task. If possible please clean all the code and format it. Best of luck 😊

**Comment by rhnas110** [comment]
Thanks for the response Sir, I just did a PR on this issue #15

**Comment by sanskarmalkhede** [comment]
Your PR is merged.
