### ISSUE TITLE
Poor CSS

### ISSUE THREAD

**Issue by madm234** [sanskarmalkhede/calculator#13]
I understand this is a initial phase of this webapp but still I would say Css is bad ,it can hurt a web developer's sentiments. Allow me to add CSS:
1. Fixing Calculator heading with proper font size and positioning.
2. Fixing background color with a linear simplistic color rather than a gradient color. It doesn't looks good though.
3. Improving input box css and -,+ button after them.
4. Your suggested changes.

If you want these changes then do assign me this issue under hactoberfest.

**Comment by madm234** [comment]
> I understand this is a initial phase of this webapp but still I would say Css is bad ,it can hurt a web developer sentiments. Allow me to add CSS:
> 
> 1. Fixing Calculator heading with proper font size and position.
> 2. Fixing background color with a linear simplistic color rather than a gradient color. It doesn't looks good.
> 3. Improving input box css and -,+ button after them.
> 
> If you want these changes then do assign me this issue under hactoberfest.

**Comment by sanskarmalkhede** [comment]
If you have again more suggestions then directly create a pull request mentioning to the issue. I will directly merge the PR if it is valid.
